export { default as authBackgroundMobile } from './bg-auth-mobile-min.png';
export { default as authBackgroundTablet } from './bg-auth-tablet-min.png';
export { default as authBackgroundLaptop } from './bg-auth-laptop-min.png';
export {default as homeBg1Mobile } from './bg1-home-mobile-min.png';
export {default as homeBg1Tablet } from './bg1-home-tablet-min.png';
export {default as homeBg1Laptop } from './bg1-home-laptop-min.png';
export {default as homeBg2Laptop } from './bg2-home-laptop-min.png';
export {default as homeBg2Tablet } from './bg2-home-tablet-min.png';
export {default as homeBg2Mobile } from './bg2-home-mobile-min.png';
export {default as homeBg3Laptop } from './bg3-home-laptop-min.png';
export {default as homeBg4Laptop } from './bg4-home-laptop-min.png';
export {default as male } from './male.svg';
export {default as female } from './female.svg';
export {default as plus } from './plus.svg';
export {default as heart } from './heart.svg';
export {default as heartFull } from './heartFull.svg';
